executable            = condorExec_syst.sh
arguments             = MC MuId 0 bkg
output                = outputMC/condor.$(ClusterId).$(ProcId).out
error                 = errorMC/condor.$(ClusterId).$(ProcId).err
log                   = logMC/condor.$(ClusterId).log
request_cpus          = 8 
request_memory		  = 16 GB
+JobFlavour           = "tomorrow"
queue

arguments = MC MuId 0 sig
queue

arguments = MC MuId 0 mass
queue

arguments = MC MuId 0 nom
queue
