executable            = condorExec.sh
arguments             = RD MuId 1 
output                = output/condor.$(ClusterId).$(ProcId).out
error                 = error/condor.$(ClusterId).$(ProcId).err
log                   = log/condor.$(ClusterId).log
request_cpus          = 8 
request_memory		  = 16 GB
+JobFlavour           = "tomorrow"
queue

arguments = RD MuId 2
queue

arguments = RD MuId 3
queue

arguments = RD MuId 4
queue

arguments = RD MuId 5
queue

arguments = RD MuId 6
queue

arguments = RD MuId 7
queue

arguments = RD MuId 8
queue

