executable            = condorExec.sh
arguments             = MC MuId 1 
output                = outputMC/condor.$(ClusterId).$(ProcId).out
error                 = errorMC/condor.$(ClusterId).$(ProcId).err
log                   = logMC/condor.$(ClusterId).log
request_cpus          = 8 
request_memory		  = 16 GB
+JobFlavour           = "tomorrow"
queue

arguments = MC MuId 2
queue

arguments = MC MuId 3
queue

arguments = MC MuId 4
queue

arguments = MC MuId 5
queue

arguments = MC MuId 6
queue

arguments = MC MuId 7
queue

arguments = MC MuId 8
queue
