executable            = condorExec.sh
arguments             = RD TrkM 1 whichFunc whichChunk 
output                = outputTrkMRD/condor.$(ClusterId).$(ProcId).out
error                 = errorTrkMRD/condor.$(ClusterId).$(ProcId).err
log                   = logTrkMRD/condor.$(ClusterId).log
request_cpus          = 8
request_memory        = 20
+JobFlavour           = "tomorrow"
queue

arguments = RD TrkM 2 whichFunc whichChunk
queue

arguments = RD TrkM 3 whichFunc whichChunk
queue

arguments = RD TrkM 4 whichFunc whichChunk
queue

arguments = RD TrkM 5 whichFunc whichChunk
queue

arguments = RD TrkM 6 whichFunc whichChunk
queue

arguments = RD TrkM 7 whichFunc whichChunk
queue

arguments = RD TrkM 8 whichFunc whichChunk
queue
