executable            = condorExec.sh
arguments             = MC 1 
output                = outputMC/condor.$(ClusterId).$(ProcId).out
error                 = errorMC/condor.$(ClusterId).$(ProcId).err
log                   = logMC/condor.$(ClusterId).log
request_cpus          = 8
request_memory        = 20g
+JobFlavour           = "tomorrow"
queue

request_cpus= 8
arguments = MC 6
queue

request_cpus= 8
arguments = MC 7
queue
