./createHTMLpageAllPlots_pdf.sh  Fits/Data/pPb/Glb_abseta09_12/
./createHTMLpageAllPlots_pdf.sh  Fits/Data/pPb/Glb_abseta00_09/
./createHTMLpageAllPlots_pdf.sh  Fits/Data/pPb/Glb_abseta12_16/
./createHTMLpageAllPlots_pdf.sh  Fits/Data/pPb/Glb_abseta16_21/
./createHTMLpageAllPlots_pdf.sh  Fits/Data/pPb/Glb_abseta21_24/
./createHTMLpageAllPlots_pdf.sh  Fits/Data/pPb/Glb_1bin/
./createHTMLpageAllPlots_pdf.sh  Fits/Data/pPb/Glb_absetadep/
./createHTMLpageAllPlots_pdf.sh  Fits/Data/pPb/Glb_etadep/
./createHTMLpageAllPlots_pdf.sh  Fits/Data/pPb/Glb_pt/
./createHTMLpageAllPlots_pdf.sh  Fits/Data/Pbp/Glb_abseta09_12/
./createHTMLpageAllPlots_pdf.sh  Fits/Data/Pbp/Glb_abseta00_09/
./createHTMLpageAllPlots_pdf.sh  Fits/Data/Pbp/Glb_abseta12_16/
./createHTMLpageAllPlots_pdf.sh  Fits/Data/Pbp/Glb_abseta16_21/
./createHTMLpageAllPlots_pdf.sh  Fits/Data/Pbp/Glb_abseta21_24/
./createHTMLpageAllPlots_pdf.sh  Fits/Data/Pbp/Glb_1bin/
./createHTMLpageAllPlots_pdf.sh  Fits/Data/Pbp/Glb_absetadep/
./createHTMLpageAllPlots_pdf.sh  Fits/Data/Pbp/Glb_etadep/
./createHTMLpageAllPlots_pdf.sh  Fits/Data/Pbp/Glb_pt/
./createHTMLpageAllPlots_pdf.sh  Fits/MC/pPb/Glb_abseta09_12/
./createHTMLpageAllPlots_pdf.sh  Fits/MC/pPb/Glb_abseta00_09/
./createHTMLpageAllPlots_pdf.sh  Fits/MC/pPb/Glb_abseta12_16/
./createHTMLpageAllPlots_pdf.sh  Fits/MC/pPb/Glb_abseta16_21/
./createHTMLpageAllPlots_pdf.sh  Fits/MC/pPb/Glb_abseta21_24/
./createHTMLpageAllPlots_pdf.sh  Fits/MC/pPb/Glb_1bin/
./createHTMLpageAllPlots_pdf.sh  Fits/MC/pPb/Glb_absetadep/
./createHTMLpageAllPlots_pdf.sh  Fits/MC/pPb/Glb_etadep/
./createHTMLpageAllPlots_pdf.sh  Fits/MC/pPb/Glb_pt/
./createHTMLpageAllPlots_pdf.sh  Fits/MC/Pbp/Glb_abseta09_12/
./createHTMLpageAllPlots_pdf.sh  Fits/MC/Pbp/Glb_abseta00_09/
./createHTMLpageAllPlots_pdf.sh  Fits/MC/Pbp/Glb_abseta12_16/
./createHTMLpageAllPlots_pdf.sh  Fits/MC/Pbp/Glb_abseta16_21/
./createHTMLpageAllPlots_pdf.sh  Fits/MC/Pbp/Glb_abseta21_24/
./createHTMLpageAllPlots_pdf.sh  Fits/MC/Pbp/Glb_1bin/
./createHTMLpageAllPlots_pdf.sh  Fits/MC/Pbp/Glb_absetadep/
./createHTMLpageAllPlots_pdf.sh  Fits/MC/Pbp/Glb_etadep/
./createHTMLpageAllPlots_pdf.sh  Fits/MC/Pbp/Glb_pt/
./createHTMLpageAllPlots_pdf.sh  Plots/Pbp_EfficiencyPlots/
./createHTMLpageAllPlots_pdf.sh  Plots/pPb_EfficiencyPlots/
